spring:
  datasource:
    url: jdbc:mysql://120.25.95.166:3306/questionnaire?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

